# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_location_country', models.CharField(choices=[('my', 'Malaysia'), ('sg', 'Singapore'), ('ph', 'Philippines'), ('th', 'Thailand')], default='Malaysia', max_length=32)),
                ('job_location_city', models.CharField(max_length=64, verbose_name='City')),
                ('job_type', models.CharField(choices=[('ft', 'Full Time'), ('pt', 'Part Time')], default='Full Time', max_length=2)),
                ('job_description', models.TextField(max_length=4000)),
                ('tag', models.CharField(max_length=64)),
                ('job_status', models.CharField(choices=[('op', 'Open'), ('cl', 'Closed')], default='Open', max_length=2)),
                ('company_name', models.CharField(max_length=64)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
