# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerjob',
            name='job_location_country',
            field=models.CharField(choices=[('Malaysia', 'Malaysia'), ('Singapore', 'Singapore'), ('Philippines', 'Philippines'), ('Thailand', 'Thailand')], default='Malaysia', max_length=32),
        ),
        migrations.AlterField(
            model_name='careerjob',
            name='job_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=32),
        ),
        migrations.AlterField(
            model_name='careerjob',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=32),
        ),
    ]
