# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_jobs', '0002_auto_20180304_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerjob',
            name='job_title',
            field=models.CharField(help_text='Minimum characters 7', max_length=255),
        ),
    ]
